### ISSUE TITLE
[Feature Request]: Enable CI for every pull request

### ISSUE THREAD

**Issue by etagwerker** [upgradejs/depngn#22]
## Expected

Every PR should run the test suite to make sure there are no regressions. 

## Current 

Every PR does not run the test suite to make sure there are no regressions. 

### Possible Implementation

It could probably look like this: 

```
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
